version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
    volumes:
      - ..:/workspace:cached
    env_file:
      - .env
    command: sleep infinity
    network_mode: host
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERDB}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSDB}
    volumes:
      - mongo:/data/db
    env_file:
      - .env
    network_mode: host

volumes:
  mongo:
